name: blog publish
on:
  push:
    branches: 
    - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.22.1] # hexo default version
    steps:
        # commit messages for repo 
        - name: Checkout
          uses: actions/checkout@master
          with:
            submodules: true
        - name: hexo deploy with-hook
          uses: yuzhishuo/hexo-deploy-with-hook@0.0.5
          env:
            PERSONAL_TOKEN: ${{ secrets.YUZHIBLOG }}
            PUBLISH_REPOSITORY: luluyuzhi/luluyuzhi.github.io # The repository the action should deploy to.
            BRANCH: master  # The branch the action should deploy to.
            PUBLISH_DIR: ./public # The folder the action should deploy.
            HOOK: ./install-slidev.sh
            PREHOOK: ./pre-install-slidev.sh
