name: Node.js CI

on:
  push:
    branches: 
    - 'main'
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
        # commit messages for repo 
        
        - name: Checkout
          uses: actions/checkout@master
          with:
            submodules: true
        - name: Build and Deploy
          uses: solybum/hexo-deploy@master
          env:
            PERSONAL_TOKEN: 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
            PUBLISH_REPOSITORY: luluyuzhi/yuzhi # The repository the action should deploy to.
            BRANCH: master  # The branch the action should deploy to.
            PUBLISH_DIR: ./public # The folder the action should deploy.
